# Generated by Django 5.2.9 on 2025-12-19 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер (до 15 цифр, можно с +)', regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
    ]
