# Generated by Django 5.2.9 on 2025-12-19 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=70000000000, error_messages={'blank': 'Пожалуйста, укажите номер телефона', 'null': 'Номер телефона не может быть пустым'}, max_length=15, validators=[django.core.validators.RegexValidator(message='Введите корректный номер (до 15 цифр, можно с +)', regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
