# Generated by Django 5.2.9 on 2026-01-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organizationdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationdata',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='organizationdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organizationdata',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='organizationdata',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='address',
            field=models.TextField(default='Не указан', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='name_organ',
            field=models.CharField(default='Не указано', max_length=200, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='ogrn',
            field=models.CharField(default='000000000000000', max_length=15, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='prav_form',
            field=models.CharField(choices=[('ooo', 'ООО'), ('ip', 'ИП')], default='ooo', max_length=3, verbose_name='Правовая форма'),
        ),
        migrations.AlterField(
            model_name='organizationdata',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
    ]
