# Generated by Django 5.2.9 on 2026-01-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_organizationdata_bank_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdata',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Полное наименование банка', max_length=100, null=True, verbose_name='Наименование банка'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='bik',
            field=models.CharField(blank=True, help_text='Банковский идентификационный код (9 цифр)', max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='checking_account',
            field=models.CharField(blank=True, help_text='Расчётный счёт организации (20 цифр)', max_length=20, null=True, verbose_name='Номер расчётного счёта'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='correspondent_account',
            field=models.CharField(blank=True, help_text='Корреспондентский счёт банка (20 цифр)', max_length=20, null=True, verbose_name='Номер корсчёта'),
        ),
    ]
